### ISSUE TITLE
Highlight the current user in ranking grid

### ISSUE THREAD

**Issue by xabikos** [xabikos/BrazilWC2014#35]

**Comment by xabikos** [comment]
I did it with the same color as admins. I am leaving this open only in case you don't like the color, in other case just close the issue.

**Comment by rogerlejeune** [comment]
Come on, that's excellent! And it's so much more efficient than I tried! I will immediately merge it to the master.

**Comment by xabikos** [comment]
I already did it!

**Comment by rogerlejeune** [comment]
I noticed. :)
