### ISSUE TITLE
Ranking position grouped by score

### ISSUE THREAD

**Issue by rogerlejeune** [xabikos/BrazilWC2014#36]
If people have the same score, they should have the same position in the ranking.

**Comment by xabikos** [comment]
Because I don't accept that I can't solve something. It took me a bit longer but I did it!!!!

**Comment by rogerlejeune** [comment]
Looking good! Only thing is... now it's not entirely correct, don't worry, we will look at it as soon as you have time. Officially, this is how it should look like:
1. ... 10 points
2. ... 9 points
(2)... 9 points
4. ... 7 points
(4) ... 7 points
(4) ... 7 points
7. ... 4 points
etc. 
I hope I haven't ruined your weekend now... :(

**Comment by xabikos** [comment]
Are you sure we want something like this? Because I thought this number should be each user's position. Now for instance we miss the third place something that is not correct

**Comment by rogerlejeune** [comment]
I get your point, but over here it's common practice, check http://en.wikipedia.org/wiki/Ranking#Standard_competition_ranking_.28.221224.22_ranking.29

**Comment by xabikos** [comment]
Ok, even though I am not convinced I think it's hard to do something like this. My suggestion is to leave it as it is and if it's confusing for the users then try to do something different.

**Comment by rogerlejeune** [comment]
I know, I will try to look at it later myself. Only thing is, if now multiple people finish on the first, second of third place, it is confusing how to distribute the money. That's why it makes more sense. But don't worry, we'll figure it out!
