### ISSUE TITLE
Create 'undo' button after calculating a match

### ISSUE THREAD

**Issue by rogerlejeune** [xabikos/BrazilWC2014#49]
I'm not sure if this is feasible, but maybe we could make an option where you select a match and 'undo' the points scored for that particular match. So essentially you do the same with the delete statement directly in the database, but now from the website itself. Another installation may have encountered a similar issue last night... what a coincidence. 
However, you may only look at this if it doesn't take too much time and you are really bored... :)

**Comment by rogerlejeune** [comment]
I tried to use some mvc stuff, but then my Visual Studio crashed... :( So I decided to create an old school example instead. Hopefully it makes sense! :)

**Comment by xabikos** [comment]
I did this merge it to master and push it. It doesn't give any feedback if the operation succeed but I guess this is not a problem as the usage of this button should be discouraged. To verify that the changed applied you can try to change the state in the match. But for sure after make the changes they should put again the match in finalized state.

**Comment by rogerlejeune** [comment]
Great stuff, man! I think they will be very happy with this feature, because sometimes apparently the results are not clear.

**Comment by rogerlejeune** [comment]
Hey dude, after updating the rankings, the page returns an error. I think it may have something to do with the two forms on one page. 
The good thing is though: everything still works. So no problems there. :)

**Comment by xabikos** [comment]
Fixed
