### ISSUE TITLE
Graphs miss last match results

### ISSUE THREAD

**Issue by rogerlejeune** [xabikos/BrazilWC2014#51]
The graphs miss the last match result, because the match was played on the 13th at 19:00, while the graph only shows items until 0:00. I think this line may have something to do with it in the rankingscontroller: 

var today = DateTime.Now > new DateTime(2014,7,13) ? new DateTime(2014,7,13) : DateTime.Now;

Is this easy to fix?

**Comment by xabikos** [comment]
Yes once again you are absolute right. I didn't change this but you can change 13 to be 14 and then everything shoud be fine. You can do it directly to master and push it to production.

By the way when do you think we should take down the sites?

**Comment by rogerlejeune** [comment]
Okay... Let me try to fix it then... :)

And I think people stop looking at it at the end of this week already. Can we make an export of everything and then shut it down at the end of the month?
